<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Movement List</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 10px; line-height: 1.35; }
        .header { text-align: center; margin-bottom: 12px; padding-bottom: 8px; border-bottom: 1px solid #ddd; }
        .title { font-size: 15px; font-weight: bold; margin-bottom: 4px; }
        .subtitle { font-size: 11px; color: #666; }
        .filters { margin-bottom: 10px; font-size: 9px; color: #666; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 4px 3px; text-align: left; border: 1px solid #ddd; vertical-align: top; }
        th { background-color: #f2f2f2; font-weight: bold; font-size: 9px; }
        .muted { color: #666; font-size: 8px; }
        .footer { margin-top: 12px; text-align: center; font-size: 8px; color: #888; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Movement List</div>
        <div class="subtitle">Generated on {{ now()->format('d M, Y H:i') }}</div>
    </div>

    @if(!empty($filterSummary))
        <div class="filters"><strong>Filters:</strong> {{ $filterSummary }}</div>
    @endif

    <table>
        <thead>
            <tr>
                <th>PIN</th>
                <th>Employee</th>
                <th>Branch</th>
                <th>Type</th>
                <th>From</th>
                <th>Return</th>
                <th>Destination</th>
                <th>Status</th>
                <th>Duration</th>
                <th>Purpose</th>
            </tr>
        </thead>
        <tbody>
            @forelse($movements as $movement)
                @php
                    $employee = $movement->employee;
                    $pin = $employee->pin ?? $employee->employee_id ?? '—';
                    $returnTime = $movement->status === 'completed' && $movement->actual_return_datetime
                        ? \Carbon\Carbon::parse($movement->actual_return_datetime)->format('d M, Y H:i')
                        : 'Not returned';
                    $duration = '—';
                    if ($movement->status === 'completed' && $movement->actual_return_datetime) {
                        $from = \Carbon\Carbon::parse($movement->from_datetime);
                        $to = \Carbon\Carbon::parse($movement->actual_return_datetime);
                        $hours = $from->diffInHours($to);
                        $minutes = $from->diffInMinutes($to) % 60;
                        $duration = "{$hours}h {$minutes}m";
                    }
                @endphp
                <tr>
                    <td>{{ $pin }}</td>
                    <td>
                        {{ $employee->name_en ?? $employee->full_name_en ?? '—' }}
                        <div class="muted">
                            {{ $employee->department->name ?? 'No Department' }},
                            {{ $employee->designation->name ?? 'No Designation' }}
                        </div>
                    </td>
                    <td>{{ $employee->branch->name ?? '—' }}</td>
                    <td>{{ ucfirst($movement->movement_type) }}</td>
                    <td>{{ \Carbon\Carbon::parse($movement->from_datetime)->format('d M, Y H:i') }}</td>
                    <td>{{ $returnTime }}</td>
                    <td>{{ $movement->destination }}</td>
                    <td>{{ ucfirst($movement->status) }}</td>
                    <td>{{ $duration }}</td>
                    <td>{{ $movement->purpose }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="10">No movements found for the selected filters.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">Report generated by HRM System</div>
</body>
</html>
