<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Monthly Attendance</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 8pt;
            line-height: 1.3;
            margin: 0;
            padding: 10px;
        }

        .header {
            text-align: center;
            margin-bottom: 15px;
        }

        .header h1 {
            font-size: 14pt;
            margin: 0 0 5px 0;
        }

        .header h2 {
            font-size: 12pt;
            margin: 0;
            color: #555;
        }

        .meta-info {
            margin-bottom: 15px;
            font-size: 8pt;
        }

        .filters {
            float: left;
        }

        .generated {
            float: right;
            color: #777;
        }

        .clearfix:after {
            content: "";
            display: table;
            clear: both;
        }

        .legend {
            margin-bottom: 10px;
            font-size: 7pt;
        }

        .legend-item {
            display: inline-block;
            margin-right: 15px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            font-size: 7pt;
        }

        th, td {
            border: 0.5px solid #ddd;
            padding: 2px;
            text-align: center;
        }

        th {
            background-color: #f5f5f5;
            font-weight: bold;
        }

        .employee-col {
            text-align: left;
            width: 120px;
        }

        .employee-name {
            font-weight: bold;
        }

        .employee-details {
            font-size: 6pt;
            color: #777;
        }

        /* Simple status colors without complex styling */
        .status-p { background-color: #d1fae5; }
        .status-a { background-color: #fee2e2; }
        .status-l { background-color: #ffedd5; }
        .status-h { background-color: #fef3c7; }
        .status-lv { background-color: #dbeafe; }
        .status-od { background-color: #e0e7ff; }

        .footer {
            margin-top: 15px;
            text-align: center;
            font-size: 7pt;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $companyName }}</h1>
        <h2>Monthly Attendance Report - {{ $month }}</h2>
    </div>

    <div class="meta-info clearfix">
        <div class="filters">
            @if($branchName || $departmentName)
                <strong>Filters:</strong>
                @if($branchName) Branch: {{ $branchName }} @endif
                @if($departmentName) @if($branchName) | @endif Department: {{ $departmentName }} @endif
            @endif
        </div>
        <div class="generated">
            Generated by: {{ $generatedBy }} | Date: {{ $generatedAt }}
        </div>
    </div>

    <div class="legend">
        <div class="legend-item">P = Present</div>
        <div class="legend-item">A = Absent</div>
        <div class="legend-item">L = Late</div>
        <div class="legend-item">H = Half Day</div>
        <div class="legend-item">LV = Leave</div>
        <div class="legend-item">OD = On Duty</div>
        <div class="legend-item">- = No Record</div>
    </div>

    <table>
        <thead>
            <tr>
                <th class="employee-col">Employee</th>
                @for ($day = 1; $day <= $daysInMonth; $day++)
                    <th>{{ $day }}</th>
                @endfor
                <th class="status-p">P</th>
                <th class="status-a">A</th>
                <th class="status-l">L</th>
                <th class="status-h">H</th>
                <th class="status-lv">LV</th>
                <th class="status-od">OD</th>
            </tr>
        </thead>
        <tbody>
            @foreach($employees as $employeeData)
                @php
                    $employee = $employeeData['employee'];
                    $summary = $employeeData['summary'];
                    $dailyStatus = $employeeData['dailyStatus'];
                @endphp
                <tr>
                    <td class="employee-col">
                        <div class="employee-name">{{ $employee->first_name }} {{ $employee->last_name }}</div>
                        <div class="employee-details">
                            {{ $employee->employee_id }} • {{ $employee->department->name }}
                        </div>
                    </td>

                    @for ($day = 1; $day <= $daysInMonth; $day++)
                        @php
                            $status = isset($dailyStatus[$day]['status']) ? $dailyStatus[$day]['status'] : null;
                            $statusClass = '';
                            $statusCode = '-';

                            if ($status === 'present') { $statusClass = 'status-p'; $statusCode = 'P'; }
                            elseif ($status === 'absent') { $statusClass = 'status-a'; $statusCode = 'A'; }
                            elseif ($status === 'late') { $statusClass = 'status-l'; $statusCode = 'L'; }
                            elseif ($status === 'half_day') { $statusClass = 'status-h'; $statusCode = 'H'; }
                            elseif ($status === 'leave') { $statusClass = 'status-lv'; $statusCode = 'LV'; }
                            elseif ($status === 'on_duty') { $statusClass = 'status-od'; $statusCode = 'OD'; }
                        @endphp
                        <td class="{{ $statusClass }}">{{ $statusCode }}</td>
                    @endfor

                    <td class="status-p">{{ $summary['present'] }}</td>
                    <td class="status-a">{{ $summary['absent'] }}</td>
                    <td class="status-l">{{ $summary['late'] }}</td>
                    <td class="status-h">{{ $summary['half_day'] }}</td>
                    <td class="status-lv">{{ $summary['leave'] }}</td>
                    <td class="status-od">{{ $summary['on_duty'] }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        {{ $companyName }} - Monthly Attendance Report {{ $month }}
    </div>
</body>
</html>
