<?php

return [
    'company_name' => env('FIXED_ASSET_REPORT_COMPANY', env('APP_NAME', 'Organization')),

    'reports' => [
        'asset-tracking' => [
            'title' => 'Asset Tracking',
            'description' => 'Current location, custodian, status, and values for all assets.',
            'group' => 'Tracking',
            'filters' => ['branch_id', 'asset_category_id', 'status'],
            'template' => 'asset-tracking',
        ],
        'asset-vendor-list' => [
            'title' => 'Asset Vendor List',
            'description' => 'Suppliers/vendors with asset count and total purchase value.',
            'group' => 'Purchase',
            'filters' => ['branch_id'],
            'template' => 'vendor-list',
        ],
        'purchase-list-branch-wise' => [
            'title' => 'Asset Purchase List (Branch Wise)',
            'description' => 'Purchases grouped and listed by branch.',
            'group' => 'Purchase',
            'filters' => ['branch_id', 'date_from', 'date_to'],
            'template' => 'purchase-list',
            'purchase_group' => 'branch',
            'date_range' => true,
        ],
        'purchase-list-category-wise' => [
            'title' => 'Asset Purchase List (Category Wise)',
            'description' => 'Purchases grouped and listed by category.',
            'group' => 'Purchase',
            'filters' => ['asset_category_id', 'branch_id', 'date_from', 'date_to'],
            'template' => 'purchase-list',
            'purchase_group' => 'category',
            'date_range' => true,
        ],
        'purchase-list-month-wise' => [
            'title' => 'Asset Purchase List (Month Wise)',
            'description' => 'Assets purchased in the selected month.',
            'group' => 'Purchase',
            'filters' => ['year', 'month', 'branch_id'],
            'template' => 'purchase-list',
            'purchase_group' => 'month',
        ],
        'asset-repair-list' => [
            'title' => 'Asset Repair List',
            'description' => 'Maintenance and repair records (corrective & other).',
            'group' => 'Operations',
            'filters' => ['date_from', 'date_to', 'branch_id'],
            'template' => 'repair-list',
            'date_range' => true,
        ],
        'asset-transfer-list' => [
            'title' => 'Asset Transfer List',
            'description' => 'Inter-branch transfers in a date range.',
            'group' => 'Operations',
            'filters' => ['date_from', 'date_to', 'branch_id'],
            'template' => 'transfer-log',
            'date_range' => true,
        ],
        'salvaged-asset-list' => [
            'title' => 'Salvaged Asset List',
            'description' => 'Assets at or near salvage value, or scrapped.',
            'group' => 'Disposal',
            'filters' => ['branch_id'],
            'template' => 'salvaged-list',
        ],
        'disposal-asset-list' => [
            'title' => 'Disposal Asset List',
            'description' => 'Approved disposal requests and disposed assets.',
            'group' => 'Disposal',
            'filters' => ['date_from', 'date_to', 'branch_id'],
            'template' => 'disposal-list',
            'date_range' => true,
        ],
        'category-wise-schedule' => [
            'title' => 'Category Wise Schedule',
            'description' => 'Depreciation register — detail by category.',
            'group' => 'Schedules',
            'filters' => ['asset_category_id', 'branch_id', 'status'],
            'template' => 'depreciation-schedule',
            'schedule_group' => 'category',
            'schedule_variant' => 'detail',
        ],
        'branch-wise-schedule' => [
            'title' => 'Branch Wise Schedule',
            'description' => 'Depreciation register — detail by branch.',
            'group' => 'Schedules',
            'filters' => ['branch_id', 'asset_category_id', 'status'],
            'template' => 'depreciation-schedule',
            'schedule_group' => 'branch',
            'schedule_variant' => 'detail',
        ],
        'category-wise-schedule-2' => [
            'title' => 'Category Wise Schedule-2',
            'description' => 'Category totals — purchase, depreciation, and book value.',
            'group' => 'Schedules',
            'filters' => ['branch_id', 'status'],
            'template' => 'depreciation-schedule',
            'schedule_group' => 'category',
            'schedule_variant' => 'summary',
        ],
        'branch-wise-schedule-2' => [
            'title' => 'Branch Wise Schedule-2',
            'description' => 'Branch totals — purchase, depreciation, and book value.',
            'group' => 'Schedules',
            'filters' => ['asset_category_id', 'status'],
            'template' => 'depreciation-schedule',
            'schedule_group' => 'branch',
            'schedule_variant' => 'summary',
        ],
        'category-wise-schedule-audit' => [
            'title' => 'Category Wise Schedule (Audit)',
            'description' => 'Audit detail with vendor, invoice, and serial numbers.',
            'group' => 'Schedules',
            'filters' => ['asset_category_id', 'branch_id', 'status'],
            'template' => 'depreciation-schedule',
            'schedule_group' => 'category',
            'schedule_variant' => 'audit',
        ],
        'branch-wise-schedule-audit' => [
            'title' => 'Branch Wise Schedule (Audit)',
            'description' => 'Audit detail by branch with vendor and invoice.',
            'group' => 'Schedules',
            'filters' => ['branch_id', 'asset_category_id', 'status'],
            'template' => 'depreciation-schedule',
            'schedule_group' => 'branch',
            'schedule_variant' => 'audit',
        ],
    ],
];
