<?php

return [
    'company_name' => env('FIXED_ASSET_REPORT_COMPANY', env('APP_NAME', 'Organization')),

    'reports' => [
        'asset-tracking' => [
            'title' => 'Asset Tracking',
            'description' => 'Asset register with purchase details, location, and current book value.',
            'group' => 'Tracking',
            'filters' => ['financial_year_id', 'branch_id', 'asset_category_id', 'date_from', 'date_to'],
            'template' => 'asset-tracking',
            'date_range' => true,
            'uses_financial_year' => true,
        ],
        'purchase-list-branch-wise' => [
            'title' => 'Asset Purchase List (Branch Wise)',
            'description' => 'Purchases grouped and listed by branch for the selected period.',
            'group' => 'Purchase',
            'filters' => ['financial_year_id', 'branch_id', 'date_from', 'date_to'],
            'template' => 'purchase-list',
            'purchase_group' => 'branch',
            'date_range' => true,
            'uses_financial_year' => true,
        ],
        'purchase-list-category-wise' => [
            'title' => 'Asset Purchase List (Category Wise)',
            'description' => 'Purchases grouped and listed by category for the selected period.',
            'group' => 'Purchase',
            'filters' => ['financial_year_id', 'asset_category_id', 'branch_id', 'date_from', 'date_to'],
            'template' => 'purchase-list',
            'purchase_group' => 'category',
            'date_range' => true,
            'uses_financial_year' => true,
        ],
        'purchase-list-month-wise' => [
            'title' => 'Asset Purchase List (Month Wise)',
            'description' => 'Assets purchased in the selected month (within financial year).',
            'group' => 'Purchase',
            'filters' => ['financial_year_id', 'year', 'month', 'branch_id'],
            'template' => 'purchase-list',
            'purchase_group' => 'month',
            'uses_financial_year' => true,
        ],
        'disposal-asset-list' => [
            'title' => 'Disposal Asset List',
            'description' => 'Disposed / written-off assets for the selected financial year.',
            'group' => 'Disposal',
            'filters' => ['financial_year_id', 'branch_id', 'asset_category_id', 'date_from', 'date_to'],
            'template' => 'disposal-list',
            'date_range' => true,
            'uses_financial_year' => true,
        ],
        'category-wise-schedule' => [
            'title' => 'Category Wise Schedule',
            'description' => 'FY depreciation schedule by category (Jul–Dec / Jan–Jun).',
            'group' => 'Schedules',
            'filters' => ['financial_year_id', 'asset_category_id', 'branch_id'],
            'template' => 'depreciation-schedule',
            'schedule_group' => 'category',
            'schedule_variant' => 'detail',
            'uses_financial_year' => true,
        ],
        'branch-wise-schedule' => [
            'title' => 'Branch Wise Schedule',
            'description' => 'FY depreciation schedule by branch (Jul–Dec / Jan–Jun).',
            'group' => 'Schedules',
            'filters' => ['financial_year_id', 'branch_id', 'asset_category_id'],
            'template' => 'depreciation-schedule',
            'schedule_group' => 'branch',
            'schedule_variant' => 'detail',
            'uses_financial_year' => true,
        ],
        'category-wise-schedule-2' => [
            'title' => 'Category Wise Schedule-2',
            'description' => 'Category movement summary — purchase, transfer, depreciation, disposal.',
            'group' => 'Schedules',
            'filters' => ['financial_year_id', 'branch_id', 'asset_category_id'],
            'template' => 'depreciation-schedule',
            'schedule_group' => 'category',
            'schedule_variant' => 'summary',
            'uses_financial_year' => true,
        ],
        'branch-wise-schedule-2' => [
            'title' => 'Branch Wise Schedule-2',
            'description' => 'Branch movement summary — purchase, transfer, depreciation, disposal.',
            'group' => 'Schedules',
            'filters' => ['financial_year_id', 'asset_category_id', 'branch_id'],
            'template' => 'depreciation-schedule',
            'schedule_group' => 'branch',
            'schedule_variant' => 'summary',
            'uses_financial_year' => true,
        ],
        'category-wise-schedule-audit' => [
            'title' => 'Category Wise Schedule (Audit)',
            'description' => 'Audit schedule by category — cost and depreciation balances for the FY.',
            'group' => 'Schedules',
            'filters' => ['financial_year_id', 'asset_category_id', 'branch_id'],
            'template' => 'depreciation-schedule',
            'schedule_group' => 'category',
            'schedule_variant' => 'audit',
            'uses_financial_year' => true,
        ],
        'branch-wise-schedule-audit' => [
            'title' => 'Branch Wise Schedule (Audit)',
            'description' => 'Audit schedule by branch — cost and depreciation balances for the FY.',
            'group' => 'Schedules',
            'filters' => ['financial_year_id', 'branch_id', 'asset_category_id'],
            'template' => 'depreciation-schedule',
            'schedule_group' => 'branch',
            'schedule_variant' => 'audit',
            'uses_financial_year' => true,
        ],
    ],
];
