<?php

return [
    'company_name' => 'MOUSUMI',
    'company_address' => 'Ukilpara, Naogaon',
    'signature_blocks' => [
        ['label' => 'Prepared By', 'department' => 'HR department'],
        ['label' => 'Verified By', 'department' => 'F & A Department'],
        ['label' => 'Approved By', 'department' => 'Executive Director'],
    ],
    'print' => [
        'rows_per_page' => 30,
        'pdf_rows_per_page' => 30,
        'margin_top_mm' => 4,
        'margin_bottom_mm' => 4,
        'margin_side_mm' => 3,
        'margin_side_extra_px' => 10,
        // Signature block offset from the bottom of each branch's last printed page.
        'signature_bottom_offset_px' => 45,
        // Blank space above each signature line for signing.
        'signature_gap_px' => 72,
        'chrome_path' => env('PAYROLL_REPORT_CHROME_PATH'),
        // Below this natural data width (ch sum), columns stretch proportionally to full page.
        'landscape_page_capacity_ch' => 195,
    ],

    'reports' => [
        'grade-step-calculation' => [
            'title' => 'Grade Step Calculation Report',
            'description' => 'Salary structure by payscale, grade and step.',
            'filters' => ['payscale_id'],
            'template' => 'grade-step',
        ],
        'salary-sheet-posted' => [
            'title' => 'Salary Sheet',
            'description' => 'Posted salary payroll for the selected period.',
            'filters' => ['year', 'month', 'branch_id', 'department_id', 'designation_id', 'program_id', 'project_id'],
            'status' => 'posted',
            'salary_type' => 'salary',
            'template' => 'salary-sheet',
            'branch_wise' => true,
        ],
        'salary-sheet-unposted' => [
            'title' => 'Salary Sheet (Un-posted)',
            'description' => 'Processed but not yet posted salary payroll.',
            'filters' => ['year', 'month', 'branch_id', 'department_id', 'designation_id', 'program_id', 'project_id'],
            'status' => 'processed',
            'salary_type' => 'salary',
            'template' => 'salary-sheet',
            'branch_wise' => true,
        ],
        'salary-sheet-employee-posted' => [
            'title' => 'Salary Sheet (Employee Wise Posted)',
            'description' => 'Posted salary for one employee.',
            'filters' => ['year', 'month', 'employee_id'],
            'status' => 'posted',
            'salary_type' => 'salary',
            'template' => 'salary-sheet',
            'branch_wise' => true,
            'require_employee' => true,
        ],
        'salary-sheet-employee-unposted' => [
            'title' => 'Salary Sheet (Employee Wise Unposted)',
            'description' => 'Processed salary for one employee.',
            'filters' => ['year', 'month', 'employee_id'],
            'status' => 'processed',
            'salary_type' => 'salary',
            'template' => 'salary-sheet',
            'branch_wise' => true,
            'require_employee' => true,
        ],
        'salary-sheet-date-range' => [
            'title' => 'Salary Sheet (Date Range)',
            'description' => 'Salary payroll between process dates.',
            'filters' => ['date_from', 'date_to', 'branch_id', 'department_id', 'designation_id'],
            'salary_type' => 'salary',
            'template' => 'salary-sheet',
            'branch_wise' => true,
            'date_range' => true,
        ],
        'salary-sheet-branch-wise' => [
            'title' => 'Salary Sheet Report (Branch Wise)',
            'description' => 'Branch topsheet: Head Office and each branch as one summary row with salary head totals.',
            'filters' => ['year', 'month', 'branch_id', 'project_id'],
            'status' => 'posted',
            'salary_type' => 'salary',
            'template' => 'salary-sheet',
            'topsheet_by' => 'branch',
        ],
        'salary-sheet-month-wise' => [
            'title' => 'Salary Sheet Report (Month Wise)',
            'description' => 'Salary sheet grouped by payroll month.',
            'filters' => ['date_from', 'date_to', 'branch_id'],
            'salary_type' => 'salary',
            'template' => 'salary-sheet-grouped',
            'group_by' => 'month',
            'date_range' => true,
        ],
        'salary-sheet-designation-wise' => [
            'title' => 'Salary Sheet Report (Designation Wise)',
            'description' => 'Salary sheet grouped by designation.',
            'filters' => ['year', 'month', 'branch_id', 'designation_id'],
            'status' => 'posted',
            'salary_type' => 'salary',
            'template' => 'salary-sheet-grouped',
            'group_by' => 'designation',
        ],
        'bank-advice' => [
            'title' => 'Bank Advice Report',
            'description' => 'Bank transfer list for posted salary.',
            'filters' => ['year', 'month', 'branch_id'],
            'status' => 'posted',
            'salary_type' => 'salary',
            'template' => 'bank-advice',
        ],
        'bank-advice-bonus' => [
            'title' => 'Bank Advice Bonus Report',
            'description' => 'Bank transfer list for posted bonus.',
            'filters' => ['year', 'month', 'branch_id'],
            'status' => 'posted',
            'salary_type' => 'bonus',
            'template' => 'bank-advice',
        ],
        'addition-register' => [
            'title' => 'Salary Addition Register',
            'description' => 'Earning components from payroll.',
            'filters' => ['year', 'month', 'branch_id', 'salary_head_id'],
            'status' => 'posted',
            'salary_type' => 'salary',
            'template' => 'head-register',
            'line_type' => 'earning',
        ],
        'deduction-register' => [
            'title' => 'Salary Deduction Register',
            'description' => 'Deduction components from payroll.',
            'filters' => ['year', 'month', 'branch_id', 'salary_head_id'],
            'status' => 'posted',
            'salary_type' => 'salary',
            'template' => 'head-register',
            'line_type' => 'deduction',
        ],
        'advance-salary' => [
            'title' => 'Advance Salary Report',
            'description' => 'Loan and advance deductions from payroll.',
            'filters' => ['year', 'month', 'branch_id', 'employee_id'],
            'status' => 'posted',
            'salary_type' => 'salary',
            'template' => 'advance-salary',
        ],
        'bonus-register' => [
            'title' => 'Bonus Register',
            'description' => 'Posted bonus payroll register.',
            'filters' => ['year', 'month', 'branch_id'],
            'status' => 'posted',
            'salary_type' => 'bonus',
            'template' => 'bonus-register',
        ],
        'final-payment' => [
            'title' => 'Final Payment Report',
            'description' => 'Date-wise PF refund, gratuity, loan recovery and net final payment statement.',
            'filters' => [
                'date_from',
                'date_to',
                'payment_status',
                'branch_id',
                'department_id',
                'designation_id',
                'program_id',
                'project_id',
            ],
            'template' => 'final-payment',
            'date_range' => true,
            'section' => 'staff-fund',
        ],
        'salary-certificate' => [
            'title' => 'Salary Certificate',
            'description' => 'Salary certificate for an employee.',
            'filters' => ['year', 'month', 'employee_id'],
            'status' => 'posted',
            'salary_type' => 'salary',
            'template' => 'salary-certificate',
            'require_employee' => true,
            'single_page' => true,
        ],
    ],
];
